executable = /usr/bin/python3
arguments = $ENV(HOME)/shared_data/montage/jobs/72_fitplane.py --program $ENV(HOME)/montage/mFitplane --input-dir $(p)/diff_p --output-dir $(p) --table $(p)/diffs_p.tbl --split $(split) --total-split $(total_splits)

initialdir = $(p)

output = 07p_fitplane.$(split).out
error = 07p_fitplane.$(split).err
log = 07p_fitplane.$(split).log

request_cpus = 1
request_memory = 3.5G

queue
